//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Teste
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        public int IdFilme { get; set; }
        public string Titulo { get; set; }
        public string Duracao { get; set; }
        public string Ano { get; set; }
        public string TipoDeMidia { get; set; }
        public string Elenco { get; set; }
        public string Diretor { get; set; }
    }
}
